### ISSUE TITLE
Data Preperation

### ISSUE THREAD

**Issue by claudiavhoof** [course-dprep/consumer-rating-insights-Yelp#10]
Prepare the data:
- Encode variables in to the right type
- Remove NA columns 
- Rename columns to a practical names
- Create dummy variables for all business attributes

**Comment by asaarloos** [comment]
git fetch origin
git checkout 10-data-preperation

**Comment by asaarloos** [comment]
**Things that already done:**

- Deleting columns that we don't use.
- Rearrange the dataset 
- Deleting companies that are permently closed
- Exploring the classes of the variables

**Things to do:**

- Dummy variables attributes
- Deleting NA's
- Barrier of the review counts
- Other preperation has to be discussed.

**Comment by asaarloos** [comment]
Fixing the structure of the document - think of packages first.
