### ISSUE TITLE
Create dummy variables 

### ISSUE THREAD

**Issue by lucia-ramos-dominguez** [course-dprep/consumer-rating-insights-Yelp#32]
Find the unique values of the string/list attributes and then make dummy variables

**Comment by asaarloos** [comment]
git fetch origin
git checkout 32-create-dummy-variables

**Comment by lucia-ramos-dominguez** [comment]
Roshini has to help us with the attribute column as it is currently a directory. I will ask again during the class

**Comment by claudiavhoof** [comment]
git fetch origin
git checkout 32-create-dummy-variables
