### ISSUE TITLE
Setting a benchmark of review count on data set

### ISSUE THREAD

**Issue by lucia-ramos-dominguez** [course-dprep/consumer-rating-insights-Yelp#33]

**Comment by asaarloos** [comment]
Ask: Roshini what is the best benchmark to size down or data.

**Comment by asaarloos** [comment]
git fetch origin
git checkout 33-setting-a-benchmark-of-review-count-on-data-set

**Comment by asaarloos** [comment]
git fetch origin
git checkout 33-setting-a-benchmark-of-review-count-on-data-set-2

I use the with folders
