### ISSUE TITLE
Seperate DataExplorations file into multiple files to prepare for automation

### ISSUE THREAD

**Issue by claudiavhoof** [course-dprep/consumer-rating-insights-Yelp#51]
Seperate the existing DataExploration file into multiple smaller files:
- Install packages and import libraries
- Import data
- Data Exploration

**Comment by lucia-ramos-dominguez** [comment]
git fetch origin
git checkout 51-seperate-dataexplorations-file-into-multiple-files-to-prepare-for-automation
