### ISSUE TITLE
Seperate DataPreperation file into multiple files to prepare for automation

### ISSUE THREAD

**Issue by claudiavhoof** [course-dprep/consumer-rating-insights-Yelp#52]
Seperate the existing DataExploration file into multiple smaller files:
- Install packages and import libraries
- Import data
- Data cleaning
- Data preporation

**Comment by lucia-ramos-dominguez** [comment]
git fetch origin
git checkout 52-seperate-datapreperation-file-into-multiple-files-to-prepare-for-automation
