### ISSUE TITLE
Group attributes in data

### ISSUE THREAD

**Issue by claudiavhoof** [course-dprep/consumer-rating-insights-Yelp#55]
Group the attributes within the data into multiple subgroups of attributes (for example: ambiance, wifi/tv, etc...) so we are able to conduct a proper analysis with larger sample sizes of observed attributes

**Comment by asaarloos** [comment]
git fetch origin
git checkout 55-group-attributes-in-data

**Comment by asaarloos** [comment]
(26-9) We have send Roshini an email, because we missing a lot of data that is now selected als NA
